/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sistema.de.hotel.pantallas;

import sistema.de.hotel.controllers.TipoDeHabitacionesController;
import javax.swing.table.DefaultTableModel;
import sistema.de.hotel.TipoDeHabitaciones;

/**
 *
 * @author harold
 */
public class RegistrarTipoDeHabitacion extends javax.swing.JPanel {

    DefaultTableModel tm = new DefaultTableModel();
    TipoDeHabitacionesController tHabitacionController = new TipoDeHabitacionesController();
    
    int id;
    
    public RegistrarTipoDeHabitacion() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPrecioTipoHabitacion = new javax.swing.JTextField();
        txtNombreTipoDeHabitacion = new javax.swing.JTextField();
        btnCrearTipo = new javax.swing.JButton();
        btnEliminarTipo = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableTipos = new javax.swing.JTable();
        lblError = new javax.swing.JLabel();
        btnActualizarTipo = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("REGISTRO DE TIPOS DE HABITACION");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel2.setText("Nombre del tipo de habitacion:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel3.setText("Precio del tipo de habitacion");

        btnCrearTipo.setText("Crear");
        btnCrearTipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearTipoMouseClicked(evt);
            }
        });
        btnCrearTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearTipoActionPerformed(evt);
            }
        });

        btnEliminarTipo.setText("Eliminar");
        btnEliminarTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTipoActionPerformed(evt);
            }
        });

        jTableTipos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Precio"
            }
        ));
        jTableTipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTiposMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTableTipos);

        btnActualizarTipo.setText("Actualizar");
        btnActualizarTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarTipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(btnCrearTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(txtPrecioTipoHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(txtNombreTipoDeHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEliminarTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnActualizarTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(115, 115, 115))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addComponent(lblError))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreTipoDeHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtPrecioTipoHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCrearTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)))
                .addComponent(lblError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizarTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearTipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearTipoMouseClicked
        //Error si no hay nombre
        if(txtNombreTipoDeHabitacion.getText().length() == 0){
            
            lblError.setText("Debes ingresar un nombre");
        //Error si no hay precio
        }else if(txtPrecioTipoHabitacion.getText().length() == 0){
            
            lblError.setText("Debes ingresar un precio");
            
        }else{
            String tipoDeHabitacion = txtNombreTipoDeHabitacion.getText();
            int precioTipoHabitacion = Integer.parseInt(txtPrecioTipoHabitacion.getText());
            int id =+ 1;
            //Creacion del objeto
            TipoDeHabitaciones tHabitacion = new TipoDeHabitaciones(precioTipoHabitacion, tipoDeHabitacion, id);
            //Añade el objeto al archivo creado
            tHabitacionController.agregarTipoDeHabitacion(tHabitacion);
            //Añade el objeto a la tabla
            tm.addRow(new Object[]{tHabitacionController.obtenerHabitaciones()});
            
            //Limpieza de las casillas de texto
            txtNombreTipoDeHabitacion.setText("");
            txtPrecioTipoHabitacion.setText("");
            //Mensaje para verificarle al usuario la accion realizada
            lblError.setText("Tipo de habitacion agregado exitosamente");
        }
        
        
        
        
    }//GEN-LAST:event_btnCrearTipoMouseClicked

    private void btnEliminarTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTipoActionPerformed
        //Elimina el tipo de habitacion de la tabla y del archivo
        tm.removeRow(jTableTipos.getSelectedRow());
        tHabitacionController.borrarTipoDeHabitacion(jTableTipos.getSelectedRow());
        //Mensaje para verificarle al usuario la accion realizada
        lblError.setText("Tipo de habitacion removido exitosamente");
        
    }//GEN-LAST:event_btnEliminarTipoActionPerformed

    private void btnActualizarTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarTipoActionPerformed
        
        
        //Error si no hay nombre
        if(txtNombreTipoDeHabitacion.getText().length() == 0){
            
            lblError.setText("Debes ingresar un nombre");
        //Error si no hay precio
        }else if(txtPrecioTipoHabitacion.getText().length() == 0){
            
            lblError.setText("Debes ingresar un precio");
            
        }else{
            
            String nuevoTipoDeHabitacion = txtNombreTipoDeHabitacion.getText();
            int nuevoPrecioTipoHabitacion = Integer.parseInt(txtPrecioTipoHabitacion.getText());
            
            
            
        TipoDeHabitaciones nuevoTHabitacion = new TipoDeHabitaciones(nuevoPrecioTipoHabitacion, nuevoTipoDeHabitacion , id);
            
        }
    }//GEN-LAST:event_btnActualizarTipoActionPerformed

    private void jTableTiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTiposMouseClicked
        
        int sr = jTableTipos.getSelectedRow();
        
        txtNombreTipoDeHabitacion.setText(tm.getValueAt(sr, 0).toString());
        txtPrecioTipoHabitacion.setText(tm.getValueAt(sr, 1).toString());
        
    }//GEN-LAST:event_jTableTiposMouseClicked

    private void btnCrearTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearTipoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarTipo;
    private javax.swing.JButton btnCrearTipo;
    private javax.swing.JButton btnEliminarTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTableTipos;
    private javax.swing.JLabel lblError;
    private javax.swing.JTextField txtNombreTipoDeHabitacion;
    private javax.swing.JTextField txtPrecioTipoHabitacion;
    // End of variables declaration//GEN-END:variables
}
