/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistema.de.hotel.pantallas;

import javax.swing.table.DefaultTableModel;
import sistema.de.hotel.TipoDeHabitaciones;
import sistema.de.hotel.controllers.TipoDeHabitacionesController;

/**
 *
 * @author Handar
 */
public class RegistrarTipoDeHabitacion1 extends javax.swing.JFrame {

        DefaultTableModel tm = new DefaultTableModel();
        TipoDeHabitacionesController tHabitacionController = new TipoDeHabitacionesController();
        
    public RegistrarTipoDeHabitacion1() {
        initComponents();
        jTableTipos.setModel(new javax.swing.table.DefaultTableModel(tHabitacionController.refrescarTabla(),new String [] {"ID", "Nombre", "Precio"}));
        
    
    int id;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableTipos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnEliminarTipo = new javax.swing.JButton();
        btnActualizarTipo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtNombreTipoDeHabitacion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPrecioTipoHabitacion = new javax.swing.JTextField();
        btnCrearTipo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("REGISTRO DE TIPOS DE HABITACION");

        lblError.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTableTipos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableTipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTiposMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTableTipos);

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnEliminarTipo.setText("Eliminar");
        btnEliminarTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTipoActionPerformed(evt);
            }
        });

        btnActualizarTipo.setText("Actualizar");
        btnActualizarTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarTipoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel2.setText("Nombre del tipo de habitacion:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel3.setText("Precio del tipo de habitacion");

        btnCrearTipo.setText("Crear");
        btnCrearTipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearTipoMouseClicked(evt);
            }
        });
        btnCrearTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearTipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(326, 326, 326)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(txtNombreTipoDeHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(txtPrecioTipoHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(btnCrearTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 255, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(99, 99, 99))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnEliminarTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(91, 91, 91)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(btnActualizarTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombreTipoDeHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(30, 30, 30)
                        .addComponent(txtPrecioTipoHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btnCrearTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnActualizarTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminarTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableTiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTiposMouseClicked
        //Facilitar la seleccion en el jTable
        int filaSeleccionada = jTableTipos.getSelectedRow();
        //Verificar que la fila si exista
        if (filaSeleccionada != -1) {

            //Convertir los objetos al tipo de dato deseado
            String nombre = (String) jTableTipos.getValueAt(filaSeleccionada, 1);
            int precio = (Integer) jTableTipos.getValueAt(filaSeleccionada, 2);

            txtNombreTipoDeHabitacion.setText(nombre);
            txtPrecioTipoHabitacion.setText(String.valueOf(precio)); //Convertir int a String para el TextField
        }
    }//GEN-LAST:event_jTableTiposMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Menu m = new Menu();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnEliminarTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTipoActionPerformed
        int filaSeleccionada = jTableTipos.getSelectedRow();

        if (filaSeleccionada != -1) { //Asegurar la seleccion

            DefaultTableModel modelo = (DefaultTableModel) jTableTipos.getModel();

            Object cellValue = modelo.getValueAt(jTableTipos.getSelectedRow(), 0);//Obtener el id de la celda

            modelo.removeRow(filaSeleccionada); // Eliminar la fila del modelo

            if (cellValue instanceof Integer) {
                //Elimina el tipo de habitacion de la tabla y del archivo
                int intValor = (Integer) cellValue;
                tHabitacionController.borrarTipoDeHabitacion(intValor);
                tHabitacionController.refrescarTabla();
                lblError.setText("Tipo de habitacion removido exitosamente");//Mensaje de exito
                txtNombreTipoDeHabitacion.setText("");
                txtPrecioTipoHabitacion.setText("");
            }else {
                lblError.setText("Debes seleccionar una fila para eliminar");//Mensaje de error
            }
        }
    }//GEN-LAST:event_btnEliminarTipoActionPerformed

    private void btnActualizarTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarTipoActionPerformed
        int filaSeleccionada = jTableTipos.getSelectedRow();

        //Verificar que la fila si exista
        if (filaSeleccionada != -1) {

            if (txtNombreTipoDeHabitacion.getText().length() == 0) {
                lblError.setText("Debes ingresar un nombre");
                //Error al no haber nada en los espacios
            }else if (txtPrecioTipoHabitacion.getText().length() == 0) {
                lblError.setText("Debes ingresar un precio");
            }else{

                int id = (int) jTableTipos.getValueAt(filaSeleccionada, 0);  //Obtener la id del objeto para modificarlo

                String nuevoNombreTipoDeHabitacion = txtNombreTipoDeHabitacion.getText();
                int nuevoPrecioTipoHabitacion = Integer.parseInt(txtPrecioTipoHabitacion.getText()); //Guardar los nuvos datos

                //Nuevo objeto par remplazar
                TipoDeHabitaciones nuevoTipoHabitacion = new TipoDeHabitaciones(nuevoPrecioTipoHabitacion, nuevoNombreTipoDeHabitacion, id);

                tHabitacionController.actualizarTipoDeHabitacion(id, nuevoTipoHabitacion);//Funcion para actualizar

                //Cambiar los datos en la tabla
                ((DefaultTableModel) jTableTipos.getModel()).setValueAt(nuevoNombreTipoDeHabitacion, filaSeleccionada, 1);
                ((DefaultTableModel) jTableTipos.getModel()).setValueAt(nuevoPrecioTipoHabitacion, filaSeleccionada, 2);

                lblError.setText("Tipo de habitación actualizado exitosamente");//Mensaje de exito
                txtNombreTipoDeHabitacion.setText("");
                txtPrecioTipoHabitacion.setText("");
            }
        }else{
            lblError.setText("Debes seleccionar una fila para actualizar"); //Mensaje de error
        }
    }//GEN-LAST:event_btnActualizarTipoActionPerformed

    private void btnCrearTipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearTipoMouseClicked
        try {

            if(txtNombreTipoDeHabitacion.getText().length() == 0){
                lblError.setText("Debe ingresar un nombre valido");
            }else if(txtPrecioTipoHabitacion.getText().length() == 0){
                lblError.setText("Debes ingresar un precio valido");
            }else{
                // Convertir el precio a int
                int precioTipoHabitacion = Integer.parseInt(txtPrecioTipoHabitacion.getText());
                // Crear el objeto Tipo De Habitaciones con el id único
                String tipoDeHabitacion = txtNombreTipoDeHabitacion.getText();
                //Generar el id
                int id = tHabitacionController.generarNuevoId();

                TipoDeHabitaciones tHabitacion = new TipoDeHabitaciones(precioTipoHabitacion, tipoDeHabitacion, id);

                // Añadir el objeto al archivo
                tHabitacionController.agregarTipoDeHabitacion(tHabitacion);

                //Refrescar tabla
                jTableTipos.setModel(new javax.swing.table.DefaultTableModel(tHabitacionController.refrescarTabla(),new String [] {"ID", "Nombre", "Precio"}));
                // Limpiar las casillas de texto
                txtNombreTipoDeHabitacion.setText("");
                txtPrecioTipoHabitacion.setText("");

                // Confirmar la acción al usuario
                lblError.setText("Tipo de habitación agregado exitosamente");
            }
        } catch (NumberFormatException e) {
            lblError.setText("El precio debe ser un número válido");//Posible error
        }
    }//GEN-LAST:event_btnCrearTipoMouseClicked

    private void btnCrearTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearTipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarTipoDeHabitacion1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarTipoDeHabitacion1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarTipoDeHabitacion1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarTipoDeHabitacion1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarTipoDeHabitacion1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarTipo;
    private javax.swing.JButton btnCrearTipo;
    private javax.swing.JButton btnEliminarTipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableTipos;
    private javax.swing.JLabel lblError;
    private javax.swing.JTextField txtNombreTipoDeHabitacion;
    private javax.swing.JTextField txtPrecioTipoHabitacion;
    // End of variables declaration//GEN-END:variables
}
